fn check_error() -> Result<(), ()> {
    Ok(())
}

fn main() {
    check_error();
}
